networks:
  website-network:
    driver: bridge

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - website-network
    depends_on:
      - app
    volumes:
      - ./nginx/nginx-certs/nginx-website.crt:/etc/ssl/nginx-website.crt
      - ./nginx/nginx-certs/nginx-website.key:/etc/ssl/nginx-website.key

  app:
    build: .
    ports:
      - "3001:3000"
    networks:
      - website-network