name: Build

on:
  pull_request:
    
jobs:
  build-app:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.2'
      - name: Install dependencies
        run: go mod download
      - name: Build app
        run: go build -ldflags "-s -w" -o app .

  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t app .