name: Build

on:
  pull_request:
    
jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8
      - name: Install Bun
        run: bun install
      - name: Compile project
        run: bun run build