name: Dependencies

on:
  pull_request:

jobs:
  check-bun-dependencies:
    name: Check Bun dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8
      - name: Install Bun
        run: bun install
      - name: Check for outdated dependencies
        run: |
          outdated=$(bun outdated)
          echo "$outdated" > result.txt
          cat result.txt
          if grep -q "-" result.txt; then
            echo "::warning ::There are outdated dependencies!"
          else
            echo "No outdated dependencies."
          fi
