on:
   workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH keys
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Podman
      run: |
        sudo apt update
        sudo apt install -y podman
        sudo apt install -y python3-pip
        pip3 install podman-compose

    - name: Shutdown website
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.REMOTE_HOST }} -p ${{ secrets.REMOTE_PORT }} << 'EOF'
          podman-compose -f docker-compose.yml down || true
        EOF