name: Test

on:
  pull_request:
    
jobs:
  build:
    name: Test app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.2'
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test ./...